export type MountainCategory = '7summits' | '8000m' | '14ers' | 'alps' | 'andes' | 'himalaya' | 'other' | 'custom';

export interface Camp {
  name: string;
  elevation: number;
}

export interface Mountain {
  id: string;
  name: string;
  elevation: number;
  elevationFt: number;
  latitude: number;
  longitude: number;
  country: string;
  range: string;
  category: MountainCategory;
  difficulty: string;
  description: string;
  firstAscent: string;
  iconEmoji: string;
  routes?: string[];
  camps?: Camp[];
}

export const categoryLabels: Record<MountainCategory, string> = {
  '7summits': '7 Summits',
  '8000m': '8000m Peaks',
  '14ers': 'Colorado 14ers',
  'alps': 'The Alps',
  'andes': 'The Andes',
  'himalaya': 'Himalaya',
  'other': 'World Classics',
  'custom': 'My Peaks',
};

export const categoryDescriptions: Record<MountainCategory, string> = {
  '7summits': 'The highest peaks on each continent',
  '8000m': 'The fourteen peaks above 8000 meters',
  '14ers': 'Colorado peaks above 14,000 feet',
  'alps': 'Iconic peaks of the European Alps',
  'andes': 'Great peaks of South America',
  'himalaya': 'Notable Himalayan peaks below 8000m',
  'other': 'Famous climbs around the world',
  'custom': 'Your personally added peaks',
};

export const mountains: Mountain[] = [
  {
    id: 'everest',
    name: 'Mount Everest',
    elevation: 8849,
    elevationFt: 29032,
    latitude: 27.9881,
    longitude: 86.9250,
    country: 'Nepal / China',
    range: 'Himalaya',
    category: '7summits',
    difficulty: 'Extreme',
    description: 'The highest mountain on Earth. Known as Sagarmatha in Nepal and Chomolungma in Tibet, Everest has been the ultimate mountaineering challenge since it was first summited in 1953.',
    firstAscent: '1953 - Edmund Hillary & Tenzing Norgay',
    iconEmoji: '🏔️',
    routes: ['South Col Route (Nepal)', 'North Ridge Route (Tibet)'],
    camps: [
      { name: 'Base Camp', elevation: 5364 },
      { name: 'Camp I', elevation: 6060 },
      { name: 'Camp II', elevation: 6400 },
      { name: 'Camp III', elevation: 7200 },
      { name: 'Camp IV / South Col', elevation: 7950 },
    ],
  },
  {
    id: 'aconcagua',
    name: 'Aconcagua',
    elevation: 6961,
    elevationFt: 22838,
    latitude: -32.6532,
    longitude: -70.0109,
    country: 'Argentina',
    range: 'Andes',
    category: '7summits',
    difficulty: 'Hard',
    description: 'The highest peak in both the Western and Southern Hemispheres. A non-technical climb via the Normal Route, but altitude and weather are serious challenges.',
    firstAscent: '1897 - Matthias Zurbriggen',
    iconEmoji: '🦅',
    routes: ['Normal Route (Northwest Ridge)', 'Polish Glacier Route', 'False Polish Route'],
    camps: [
      { name: 'Confluencia', elevation: 3390 },
      { name: 'Plaza de Mulas', elevation: 4370 },
      { name: 'Camp I / Canada', elevation: 4910 },
      { name: 'Camp II / Nido de Cóndores', elevation: 5380 },
      { name: 'Camp III / Colera', elevation: 5970 },
    ],
  },
  {
    id: 'denali',
    name: 'Denali',
    elevation: 6190,
    elevationFt: 20310,
    latitude: 63.0695,
    longitude: -151.0074,
    country: 'USA (Alaska)',
    range: 'Alaska Range',
    category: '7summits',
    difficulty: 'Hard',
    description: 'The highest peak in North America. Known for extreme cold and weather, Denali has one of the largest base-to-summit rises of any mountain on Earth.',
    firstAscent: '1913 - Hudson Stuck & team',
    iconEmoji: '🐻',
    routes: ['West Buttress', 'West Rib', 'Cassin Ridge'],
    camps: [
      { name: 'Base Camp', elevation: 2195 },
      { name: 'Camp I / 7,800ft', elevation: 2377 },
      { name: 'Camp II / 9,500ft', elevation: 2896 },
      { name: 'Camp III / 11,000ft', elevation: 3353 },
      { name: 'Camp IV / 14,200ft', elevation: 4328 },
      { name: 'High Camp / 17,200ft', elevation: 5243 },
    ],
  },
  {
    id: 'kilimanjaro',
    name: 'Mount Kilimanjaro',
    elevation: 5895,
    elevationFt: 19341,
    latitude: -3.0674,
    longitude: 37.3556,
    country: 'Tanzania',
    range: 'Eastern Rift Mountains',
    category: '7summits',
    difficulty: 'Moderate',
    description: 'Africa\'s highest peak and the world\'s tallest freestanding mountain. A volcanic massif with three cones: Kibo, Mawenzi, and Shira.',
    firstAscent: '1889 - Hans Meyer & Ludwig Purtscheller',
    iconEmoji: '🌋',
    routes: ['Marangu Route', 'Machame Route', 'Lemosho Route', 'Rongai Route'],
    camps: [
      { name: 'Mandara Hut', elevation: 2700 },
      { name: 'Horombo Hut', elevation: 3720 },
      { name: 'Kibo Hut', elevation: 4703 },
    ],
  },
  {
    id: 'elbrus',
    name: 'Mount Elbrus',
    elevation: 5642,
    elevationFt: 18510,
    latitude: 43.3499,
    longitude: 42.4453,
    country: 'Russia',
    range: 'Caucasus',
    category: '7summits',
    difficulty: 'Moderate',
    description: 'The highest peak in Europe (when the Caucasus is considered part of Europe). A dormant volcano with twin summits covered in permanent ice.',
    firstAscent: '1874 - Florence Crauford Grove & team',
    iconEmoji: '❄️',
    routes: ['South Route (Barrels Hut)', 'North Route'],
    camps: [
      { name: 'Barrels Hut', elevation: 3890 },
      { name: 'Pastukhov Rocks', elevation: 4670 },
    ],
  },
  {
    id: 'vinson',
    name: 'Vinson Massif',
    elevation: 4892,
    elevationFt: 16050,
    latitude: -78.5254,
    longitude: -85.6171,
    country: 'Antarctica',
    range: 'Sentinel Range',
    category: '7summits',
    difficulty: 'Hard',
    description: 'The highest peak in Antarctica. Remote and extremely cold, reaching Vinson requires flying to a base camp on the ice from Punta Arenas, Chile.',
    firstAscent: '1966 - Nicholas Clinch & team',
    iconEmoji: '🧊',
    routes: ['Normal Route (Branscomb Glacier)'],
    camps: [
      { name: 'Base Camp', elevation: 2140 },
      { name: 'Low Camp', elevation: 2770 },
      { name: 'High Camp', elevation: 3730 },
    ],
  },
  {
    id: 'carstensz',
    name: 'Carstensz Pyramid',
    elevation: 4884,
    elevationFt: 16024,
    latitude: -4.0833,
    longitude: 137.1833,
    country: 'Indonesia',
    range: 'Sudirman Range',
    category: '7summits',
    difficulty: 'Hard',
    description: 'The highest peak in Oceania. A limestone spire requiring technical rock climbing, located in the remote highlands of Papua.',
    firstAscent: '1962 - Heinrich Harrer & team',
    iconEmoji: '🪨',
    routes: ['Standard Route (North Face)'],
    camps: [
      { name: 'Base Camp', elevation: 4260 },
      { name: 'High Camp area', elevation: 4500 },
    ],
  },
  {
    id: 'k2',
    name: 'K2',
    elevation: 8611,
    elevationFt: 28251,
    latitude: 35.8800,
    longitude: 76.5133,
    country: 'Pakistan / China',
    range: 'Karakoram',
    category: '8000m',
    difficulty: 'Extreme',
    description: 'The second highest and arguably the most dangerous mountain in the world. Known as the "Savage Mountain" for its extreme difficulty and high fatality rate.',
    firstAscent: '1954 - Achille Compagnoni & Lino Lacedelli',
    iconEmoji: '⚡',
    routes: ['Abruzzi Spur', 'Cesen Route', 'Magic Line'],
    camps: [
      { name: 'Base Camp', elevation: 5150 },
      { name: 'Camp I', elevation: 6050 },
      { name: 'Camp II', elevation: 6700 },
      { name: 'Camp III', elevation: 7200 },
      { name: 'Camp IV', elevation: 7950 },
    ],
  },
  {
    id: 'kangchenjunga',
    name: 'Kangchenjunga',
    elevation: 8586,
    elevationFt: 28169,
    latitude: 27.7025,
    longitude: 88.1475,
    country: 'Nepal / India',
    range: 'Himalaya',
    category: '8000m',
    difficulty: 'Extreme',
    description: 'The third highest mountain in the world. Sacred to the people of Sikkim, climbers traditionally stop just below the summit out of respect.',
    firstAscent: '1955 - Joe Brown & George Band',
    iconEmoji: '🙏',
    routes: ['Southwest Face', 'North Face'],
    camps: [
      { name: 'Base Camp', elevation: 5140 },
      { name: 'Camp I', elevation: 5900 },
      { name: 'Camp II', elevation: 6500 },
      { name: 'Camp III', elevation: 7200 },
      { name: 'Camp IV', elevation: 7900 },
    ],
  },
  {
    id: 'lhotse',
    name: 'Lhotse',
    elevation: 8516,
    elevationFt: 27940,
    latitude: 27.9617,
    longitude: 86.9333,
    country: 'Nepal / China',
    range: 'Himalaya',
    category: '8000m',
    difficulty: 'Extreme',
    description: 'The fourth highest mountain in the world, connected to Everest via the South Col. Its south face is one of the steepest walls in mountaineering.',
    firstAscent: '1956 - Ernst Reiss & Fritz Luchsinger',
    iconEmoji: '🔺',
    routes: ['West Face / Lhotse Couloir'],
    camps: [
      { name: 'Base Camp', elevation: 5364 },
      { name: 'Camp I', elevation: 6060 },
      { name: 'Camp II', elevation: 6400 },
      { name: 'Camp III', elevation: 7200 },
      { name: 'Camp IV / South Col', elevation: 7950 },
    ],
  },
  {
    id: 'makalu',
    name: 'Makalu',
    elevation: 8485,
    elevationFt: 27838,
    latitude: 27.8897,
    longitude: 87.0886,
    country: 'Nepal / China',
    range: 'Himalaya',
    category: '8000m',
    difficulty: 'Extreme',
    description: 'The fifth highest mountain in the world. An isolated peak with a distinctive four-sided pyramid shape, known for its steep pitches and exposed ridges.',
    firstAscent: '1955 - Jean Couzy & Lionel Terray',
    iconEmoji: '💎',
    routes: ['Northwest Ridge', 'West Face'],
    camps: [
      { name: 'Base Camp', elevation: 4870 },
      { name: 'Camp I', elevation: 5700 },
      { name: 'Camp II', elevation: 6400 },
      { name: 'Camp III', elevation: 7400 },
    ],
  },
  {
    id: 'cho-oyu',
    name: 'Cho Oyu',
    elevation: 8188,
    elevationFt: 26864,
    latitude: 28.0942,
    longitude: 86.6608,
    country: 'Nepal / China',
    range: 'Himalaya',
    category: '8000m',
    difficulty: 'Hard',
    description: 'The sixth highest mountain in the world. Considered the easiest 8000m peak, it is often used as preparation for Everest.',
    firstAscent: '1954 - Herbert Tichy, Joseph Jöchler & Pasang Dawa Lama',
    iconEmoji: '🌬️',
    routes: ['Normal Route (Northwest Face)'],
    camps: [
      { name: 'Base Camp', elevation: 5650 },
      { name: 'Camp I', elevation: 6400 },
      { name: 'Camp II', elevation: 7100 },
      { name: 'Camp III', elevation: 7500 },
    ],
  },
  {
    id: 'dhaulagiri',
    name: 'Dhaulagiri',
    elevation: 8167,
    elevationFt: 26795,
    latitude: 28.6967,
    longitude: 83.4875,
    country: 'Nepal',
    range: 'Himalaya',
    category: '8000m',
    difficulty: 'Extreme',
    description: 'The seventh highest mountain in the world. Its name means "White Mountain" and it held the record as the world\'s highest known peak for 30 years.',
    firstAscent: '1960 - Kurt Diemberger & team',
    iconEmoji: '🏳️',
    routes: ['Northeast Ridge'],
    camps: [
      { name: 'Base Camp', elevation: 4700 },
      { name: 'Camp I', elevation: 5900 },
      { name: 'Camp II', elevation: 6400 },
      { name: 'Camp III', elevation: 7400 },
    ],
  },
  {
    id: 'manaslu',
    name: 'Manaslu',
    elevation: 8163,
    elevationFt: 26781,
    latitude: 28.5497,
    longitude: 84.5597,
    country: 'Nepal',
    range: 'Himalaya',
    category: '8000m',
    difficulty: 'Hard',
    description: 'The eighth highest mountain in the world. Known as the "Mountain of the Spirit," it has become increasingly popular as an alternative to Everest.',
    firstAscent: '1956 - Toshio Imanishi & Gyalzen Norbu',
    iconEmoji: '👻',
    routes: ['Northeast Face'],
    camps: [
      { name: 'Base Camp', elevation: 4800 },
      { name: 'Camp I', elevation: 5700 },
      { name: 'Camp II', elevation: 6300 },
      { name: 'Camp III', elevation: 6800 },
      { name: 'Camp IV', elevation: 7400 },
    ],
  },
  {
    id: 'nanga-parbat',
    name: 'Nanga Parbat',
    elevation: 8126,
    elevationFt: 26660,
    latitude: 35.2375,
    longitude: 74.5892,
    country: 'Pakistan',
    range: 'Himalaya',
    category: '8000m',
    difficulty: 'Extreme',
    description: 'The ninth highest mountain in the world. Known as the "Killer Mountain" for its extremely high fatality rate among climbers. Features the largest mountain face on Earth.',
    firstAscent: '1953 - Hermann Buhl (solo)',
    iconEmoji: '💀',
    routes: ['Kinshofer Route', 'Diamir Face', 'Mazeno Ridge'],
    camps: [
      { name: 'Base Camp', elevation: 4100 },
      { name: 'Camp I', elevation: 4900 },
      { name: 'Camp II', elevation: 6000 },
      { name: 'Camp III', elevation: 6600 },
      { name: 'Camp IV', elevation: 7200 },
    ],
  },
  {
    id: 'annapurna',
    name: 'Annapurna I',
    elevation: 8091,
    elevationFt: 26545,
    latitude: 28.5961,
    longitude: 83.8203,
    country: 'Nepal',
    range: 'Himalaya',
    category: '8000m',
    difficulty: 'Extreme',
    description: 'The tenth highest mountain with the highest fatality-to-summit ratio of any 8000m peak. The first 8000m peak ever climbed.',
    firstAscent: '1950 - Maurice Herzog & Louis Lachenal',
    iconEmoji: '🔥',
    routes: ['North Face', 'South Face'],
    camps: [
      { name: 'Base Camp', elevation: 4130 },
      { name: 'Camp I', elevation: 5000 },
      { name: 'Camp II', elevation: 5600 },
      { name: 'Camp III', elevation: 6300 },
      { name: 'Camp IV', elevation: 7100 },
    ],
  },
  {
    id: 'gasherbrum1',
    name: 'Gasherbrum I',
    elevation: 8080,
    elevationFt: 26509,
    latitude: 35.7244,
    longitude: 76.6933,
    country: 'Pakistan / China',
    range: 'Karakoram',
    category: '8000m',
    difficulty: 'Extreme',
    description: 'Also known as Hidden Peak, the 11th highest mountain in the world. Its name means "Beautiful Mountain" in Balti language.',
    firstAscent: '1958 - Pete Schoening & Andy Kauffman',
    iconEmoji: '🌟',
    routes: ['Japanese Couloir'],
    camps: [
      { name: 'Base Camp', elevation: 5100 },
      { name: 'Camp I', elevation: 6000 },
      { name: 'Camp II', elevation: 6600 },
      { name: 'Camp III', elevation: 7100 },
    ],
  },
  {
    id: 'broad-peak',
    name: 'Broad Peak',
    elevation: 8051,
    elevationFt: 26414,
    latitude: 35.8117,
    longitude: 76.5653,
    country: 'Pakistan / China',
    range: 'Karakoram',
    category: '8000m',
    difficulty: 'Extreme',
    description: 'The 12th highest mountain, named for its broad summit. The first 8000m peak climbed without supplemental oxygen or high-altitude porters.',
    firstAscent: '1957 - Fritz Wintersteller & team',
    iconEmoji: '📐',
    routes: ['West Ridge'],
    camps: [
      { name: 'Base Camp', elevation: 5000 },
      { name: 'Camp I', elevation: 6000 },
      { name: 'Camp II', elevation: 6600 },
      { name: 'Camp III', elevation: 7200 },
    ],
  },
  {
    id: 'gasherbrum2',
    name: 'Gasherbrum II',
    elevation: 8035,
    elevationFt: 26362,
    latitude: 35.7583,
    longitude: 76.6533,
    country: 'Pakistan / China',
    range: 'Karakoram',
    category: '8000m',
    difficulty: 'Hard',
    description: 'The 13th highest mountain and one of the more accessible 8000m peaks in the Karakoram. A popular stepping stone for higher Karakoram objectives.',
    firstAscent: '1956 - Fritz Moravec & team',
    iconEmoji: '🗻',
    routes: ['Southwest Ridge'],
    camps: [
      { name: 'Base Camp', elevation: 5100 },
      { name: 'Camp I', elevation: 6100 },
      { name: 'Camp II', elevation: 6600 },
      { name: 'Camp III', elevation: 7000 },
    ],
  },
  {
    id: 'shishapangma',
    name: 'Shishapangma',
    elevation: 8027,
    elevationFt: 26335,
    latitude: 28.3525,
    longitude: 85.7797,
    country: 'China (Tibet)',
    range: 'Himalaya',
    category: '8000m',
    difficulty: 'Hard',
    description: 'The 14th highest mountain and the lowest of the 8000m peaks. The last 8000m peak to be climbed, as it lies entirely within Tibet.',
    firstAscent: '1964 - Xu Jing & team',
    iconEmoji: '🐉',
    routes: ['Northwest Face'],
    camps: [
      { name: 'Base Camp', elevation: 5000 },
      { name: 'Camp I', elevation: 5800 },
      { name: 'Camp II', elevation: 6400 },
      { name: 'Camp III', elevation: 7200 },
    ],
  },
  {
    id: 'mt-elbert',
    name: 'Mount Elbert',
    elevation: 4401,
    elevationFt: 14440,
    latitude: 39.1178,
    longitude: -106.4453,
    country: 'USA (Colorado)',
    range: 'Sawatch Range',
    category: '14ers',
    difficulty: 'Easy',
    description: 'The highest peak in Colorado and the Rocky Mountains. A popular non-technical hike with well-maintained trails.',
    firstAscent: '1874 - H.W.V. Stuckle',
    iconEmoji: '🦌',
  },
  {
    id: 'mt-massive',
    name: 'Mount Massive',
    elevation: 4396,
    elevationFt: 14428,
    latitude: 39.1875,
    longitude: -106.4756,
    country: 'USA (Colorado)',
    range: 'Sawatch Range',
    category: '14ers',
    difficulty: 'Easy',
    description: 'The second highest peak in Colorado. Named for its massive bulk—it has the most area above 14,000 feet of any peak in the contiguous US.',
    firstAscent: '1873 - Henry Gannett',
    iconEmoji: '🏕️',
  },
  {
    id: 'mt-harvard',
    name: 'Mount Harvard',
    elevation: 4395,
    elevationFt: 14421,
    latitude: 38.9244,
    longitude: -106.3208,
    country: 'USA (Colorado)',
    range: 'Sawatch Range',
    category: '14ers',
    difficulty: 'Moderate',
    description: 'The third highest peak in Colorado, named after Harvard University by members of a survey party who were alumni.',
    firstAscent: '1869 - J.D. Whitney survey',
    iconEmoji: '📚',
  },
  {
    id: 'blanca-peak',
    name: 'Blanca Peak',
    elevation: 4374,
    elevationFt: 14351,
    latitude: 37.5775,
    longitude: -105.4856,
    country: 'USA (Colorado)',
    range: 'Sangre de Cristo',
    category: '14ers',
    difficulty: 'Moderate',
    description: 'The fourth highest peak in Colorado. Sacred to the Navajo people as the eastern boundary of their homeland.',
    firstAscent: '1874 - Survey team',
    iconEmoji: '🦅',
  },
  {
    id: 'la-plata',
    name: 'La Plata Peak',
    elevation: 4372,
    elevationFt: 14343,
    latitude: 39.0294,
    longitude: -106.4731,
    country: 'USA (Colorado)',
    range: 'Sawatch Range',
    category: '14ers',
    difficulty: 'Moderate',
    description: 'The fifth highest peak in Colorado. Its name means "silver" in Spanish, reflecting the mining heritage of the region.',
    firstAscent: '1873 - Survey team',
    iconEmoji: '🪙',
  },
  {
    id: 'uncompahgre',
    name: 'Uncompahgre Peak',
    elevation: 4361,
    elevationFt: 14321,
    latitude: 38.0717,
    longitude: -107.4622,
    country: 'USA (Colorado)',
    range: 'San Juan Mountains',
    category: '14ers',
    difficulty: 'Easy',
    description: 'The highest peak in the San Juan Mountains and sixth highest in Colorado. Known for its flat summit area.',
    firstAscent: '1874 - Survey team',
    iconEmoji: '🏜️',
  },
  {
    id: 'crestone-peak',
    name: 'Crestone Peak',
    elevation: 4357,
    elevationFt: 14300,
    latitude: 37.9667,
    longitude: -105.5853,
    country: 'USA (Colorado)',
    range: 'Sangre de Cristo',
    category: '14ers',
    difficulty: 'Hard',
    description: 'One of Colorado\'s most challenging 14ers. The standard route involves Class 3 scrambling with significant exposure.',
    firstAscent: '1916 - Albert Ellingwood & Eleanor Davis',
    iconEmoji: '⛏️',
  },
  {
    id: 'mt-lincoln',
    name: 'Mount Lincoln',
    elevation: 4354,
    elevationFt: 14293,
    latitude: 39.3514,
    longitude: -106.1114,
    country: 'USA (Colorado)',
    range: 'Mosquito Range',
    category: '14ers',
    difficulty: 'Easy',
    description: 'Named after President Abraham Lincoln. Part of a popular loop that includes four 14ers in one day.',
    firstAscent: '1861 - Survey team',
    iconEmoji: '🎩',
  },
  {
    id: 'grays-peak',
    name: 'Grays Peak',
    elevation: 4352,
    elevationFt: 14278,
    latitude: 39.6339,
    longitude: -105.8178,
    country: 'USA (Colorado)',
    range: 'Front Range',
    category: '14ers',
    difficulty: 'Easy',
    description: 'The highest point on the Continental Divide in North America. One of the most popular 14ers due to proximity to Denver.',
    firstAscent: '1861 - Charles C. Parry',
    iconEmoji: '🧭',
  },
  {
    id: 'torreys-peak',
    name: 'Torreys Peak',
    elevation: 4349,
    elevationFt: 14275,
    latitude: 39.6428,
    longitude: -105.8211,
    country: 'USA (Colorado)',
    range: 'Front Range',
    category: '14ers',
    difficulty: 'Easy',
    description: 'Often climbed together with neighboring Grays Peak via a short saddle traverse. Named after botanist John Torrey.',
    firstAscent: '1861 - Charles C. Parry',
    iconEmoji: '🌿',
  },
  {
    id: 'quandary-peak',
    name: 'Quandary Peak',
    elevation: 4348,
    elevationFt: 14271,
    latitude: 39.3972,
    longitude: -106.1064,
    country: 'USA (Colorado)',
    range: 'Tenmile Range',
    category: '14ers',
    difficulty: 'Easy',
    description: 'One of the most accessible and popular 14ers in Colorado. The East Ridge trail is a well-traveled Class 1 route.',
    firstAscent: '1861 - Survey team',
    iconEmoji: '🎿',
  },
  {
    id: 'longs-peak',
    name: 'Longs Peak',
    elevation: 4346,
    elevationFt: 14259,
    latitude: 40.2550,
    longitude: -105.6156,
    country: 'USA (Colorado)',
    range: 'Front Range',
    category: '14ers',
    difficulty: 'Hard',
    description: 'The northernmost 14er in Colorado and centerpiece of Rocky Mountain National Park. The Keyhole Route is a classic and demanding scramble.',
    firstAscent: '1868 - John Wesley Powell & team',
    iconEmoji: '🔑',
  },
  {
    id: 'pikes-peak',
    name: 'Pikes Peak',
    elevation: 4302,
    elevationFt: 14115,
    latitude: 38.8409,
    longitude: -105.0423,
    country: 'USA (Colorado)',
    range: 'Front Range',
    category: '14ers',
    difficulty: 'Moderate',
    description: 'America\'s Mountain—inspired the song "America the Beautiful." One of the most visited peaks in North America with a road and cog railway to the top.',
    firstAscent: '1820 - Edwin James',
    iconEmoji: '🇺🇸',
  },
  {
    id: 'capitol-peak',
    name: 'Capitol Peak',
    elevation: 4307,
    elevationFt: 14131,
    latitude: 39.1503,
    longitude: -107.0831,
    country: 'USA (Colorado)',
    range: 'Elk Mountains',
    category: '14ers',
    difficulty: 'Hard',
    description: 'Widely considered the most difficult standard 14er route in Colorado. Features the famous "Knife Edge" traverse with extreme exposure.',
    firstAscent: '1909 - Percy Hagerman & Harold Clark',
    iconEmoji: '🗡️',
  },
  {
    id: 'maroon-peak',
    name: 'Maroon Peak',
    elevation: 4315,
    elevationFt: 14163,
    latitude: 39.0708,
    longitude: -106.9889,
    country: 'USA (Colorado)',
    range: 'Elk Mountains',
    category: '14ers',
    difficulty: 'Hard',
    description: 'Part of the iconic Maroon Bells. Known as one of the "Deadly Bells" due to its crumbly, unstable rock that has claimed many lives.',
    firstAscent: '1908 - Percy Hagerman',
    iconEmoji: '🔔',
  },
  {
    id: 'mont-blanc',
    name: 'Mont Blanc',
    elevation: 4809,
    elevationFt: 15777,
    latitude: 45.8326,
    longitude: 6.8652,
    country: 'France / Italy',
    range: 'Alps',
    category: 'alps',
    difficulty: 'Hard',
    description: 'The highest peak in the Alps and Western Europe. The birthplace of mountaineering, first climbed in 1786. Over 20,000 people attempt it annually.',
    firstAscent: '1786 - Jacques Balmat & Michel Paccard',
    iconEmoji: '👑',
    routes: ['Goûter Route', 'Trois Monts Route', 'Cosmiques Route'],
    camps: [
      { name: 'Tête Rousse Hut', elevation: 3167 },
      { name: 'Goûter Hut', elevation: 3817 },
      { name: 'Cosmiques Hut', elevation: 3613 },
      { name: 'Grands Mulets Hut', elevation: 3051 },
    ],
  },
  {
    id: 'matterhorn',
    name: 'Matterhorn',
    elevation: 4478,
    elevationFt: 14692,
    latitude: 45.9764,
    longitude: 7.6586,
    country: 'Switzerland / Italy',
    range: 'Alps',
    category: 'alps',
    difficulty: 'Hard',
    description: 'Perhaps the most iconic mountain in the world. Its distinctive pyramidal shape makes it one of the most photographed mountains. The Hörnli Ridge is the standard route.',
    firstAscent: '1865 - Edward Whymper & team',
    iconEmoji: '🍫',
    routes: ['Hörnli Ridge', 'Lion Ridge (Italian)', 'Zmutt Ridge'],
    camps: [
      { name: 'Hörnli Hut', elevation: 3260 },
      { name: 'Solvay Hut', elevation: 4003 },
      { name: 'Carrel Hut', elevation: 3830 },
    ],
  },
  {
    id: 'eiger',
    name: 'Eiger',
    elevation: 3967,
    elevationFt: 13015,
    latitude: 46.5775,
    longitude: 8.0053,
    country: 'Switzerland',
    range: 'Bernese Alps',
    category: 'alps',
    difficulty: 'Extreme',
    description: 'Famous for its treacherous North Face, known as the "Mordwand" (Murder Wall). The North Face is considered one of the great north faces of the Alps.',
    firstAscent: '1858 - Charles Barrington & guides',
    iconEmoji: '🧗',
    routes: ['Mittellegi Ridge', '1938 Route (North Face)'],
    camps: [
      { name: 'Mittellegi Hut', elevation: 3355 },
      { name: 'Eigergletscher', elevation: 2320 },
    ],
  },
  {
    id: 'jungfrau',
    name: 'Jungfrau',
    elevation: 4158,
    elevationFt: 13642,
    latitude: 46.5367,
    longitude: 7.9614,
    country: 'Switzerland',
    range: 'Bernese Alps',
    category: 'alps',
    difficulty: 'Hard',
    description: 'Part of the famous Eiger-Mönch-Jungfrau trio. Its name means "Young Woman" and it has been a UNESCO World Heritage Site since 2001.',
    firstAscent: '1811 - Johann Rudolf & Hieronymus Meyer',
    iconEmoji: '👸',
  },
  {
    id: 'gran-paradiso',
    name: 'Gran Paradiso',
    elevation: 4061,
    elevationFt: 13323,
    latitude: 45.5181,
    longitude: 7.2661,
    country: 'Italy',
    range: 'Graian Alps',
    category: 'alps',
    difficulty: 'Moderate',
    description: 'The highest mountain entirely within Italy. Located in Gran Paradiso National Park, Italy\'s oldest national park.',
    firstAscent: '1860 - John Jeremy Cowell & team',
    iconEmoji: '🦊',
  },
  {
    id: 'monte-rosa',
    name: 'Monte Rosa (Dufourspitze)',
    elevation: 4634,
    elevationFt: 15203,
    latitude: 45.9368,
    longitude: 7.8667,
    country: 'Switzerland / Italy',
    range: 'Pennine Alps',
    category: 'alps',
    difficulty: 'Hard',
    description: 'The second highest peak in the Alps. Dufourspitze is the highest of Monte Rosa\'s many summits and the highest point in Switzerland.',
    firstAscent: '1855 - Charles Hudson & team',
    iconEmoji: '🌹',
  },
  {
    id: 'weisshorn',
    name: 'Weisshorn',
    elevation: 4506,
    elevationFt: 14783,
    latitude: 46.1067,
    longitude: 7.7164,
    country: 'Switzerland',
    range: 'Pennine Alps',
    category: 'alps',
    difficulty: 'Hard',
    description: 'One of the most beautiful peaks in the Alps with its elegant pyramidal shape. Considered one of the finest mountaineering challenges in Switzerland.',
    firstAscent: '1861 - John Tyndall & team',
    iconEmoji: '🤍',
  },
  {
    id: 'dom',
    name: 'Dom',
    elevation: 4545,
    elevationFt: 14912,
    latitude: 46.0908,
    longitude: 7.8583,
    country: 'Switzerland',
    range: 'Pennine Alps',
    category: 'alps',
    difficulty: 'Hard',
    description: 'The highest mountain entirely within Switzerland and the third highest in the Alps. Part of the Mischabel group.',
    firstAscent: '1858 - J. Llewelyn Davies & team',
    iconEmoji: '⛪',
  },
  {
    id: 'grossglockner',
    name: 'Grossglockner',
    elevation: 3798,
    elevationFt: 12461,
    latitude: 47.0742,
    longitude: 12.6947,
    country: 'Austria',
    range: 'Hohe Tauern',
    category: 'alps',
    difficulty: 'Moderate',
    description: 'The highest mountain in Austria. Known for the famous Grossglockner High Alpine Road and the Pasterze glacier at its base.',
    firstAscent: '1800 - Martin Reicher & team',
    iconEmoji: '🇦🇹',
  },
  {
    id: 'zugspitze',
    name: 'Zugspitze',
    elevation: 2962,
    elevationFt: 9718,
    latitude: 47.4211,
    longitude: 10.9853,
    country: 'Germany / Austria',
    range: 'Wetterstein Alps',
    category: 'alps',
    difficulty: 'Moderate',
    description: 'The highest peak in Germany. Accessible by cable car, but the climbing routes offer classic alpine experiences. Features a glacier ski area.',
    firstAscent: '1820 - Josef Naus & team',
    iconEmoji: '🚡',
  },
  {
    id: 'dent-blanche',
    name: 'Dent Blanche',
    elevation: 4357,
    elevationFt: 14295,
    latitude: 46.0367,
    longitude: 7.6044,
    country: 'Switzerland',
    range: 'Pennine Alps',
    category: 'alps',
    difficulty: 'Hard',
    description: 'A striking isolated peak in the Pennine Alps. Its South Ridge is one of the classic alpine routes, requiring solid mixed climbing skills.',
    firstAscent: '1862 - Thomas Stuart Kennedy & team',
    iconEmoji: '🦷',
  },
  {
    id: 'aiguille-verte',
    name: 'Aiguille Verte',
    elevation: 4122,
    elevationFt: 13524,
    latitude: 45.9383,
    longitude: 6.8650,
    country: 'France',
    range: 'Mont Blanc Massif',
    category: 'alps',
    difficulty: 'Hard',
    description: 'A technically challenging peak in the Mont Blanc massif. The Whymper Couloir is the standard route, a steep snow/ice climb.',
    firstAscent: '1865 - Edward Whymper & guides',
    iconEmoji: '💚',
  },
  {
    id: 'grandes-jorasses',
    name: 'Grandes Jorasses',
    elevation: 4208,
    elevationFt: 13806,
    latitude: 45.8681,
    longitude: 6.9842,
    country: 'France / Italy',
    range: 'Mont Blanc Massif',
    category: 'alps',
    difficulty: 'Extreme',
    description: 'Famous for its North Face, one of the three great north faces of the Alps. The Walker Spur is one of the most coveted routes in alpinism.',
    firstAscent: '1868 - Edward Whymper & team',
    iconEmoji: '🧱',
  },
  {
    id: 'triglav',
    name: 'Triglav',
    elevation: 2864,
    elevationFt: 9396,
    latitude: 46.3786,
    longitude: 13.8364,
    country: 'Slovenia',
    range: 'Julian Alps',
    category: 'alps',
    difficulty: 'Moderate',
    description: 'The highest peak in Slovenia and symbol of the nation (featured on its flag and coat of arms). A national pilgrimage for Slovenians.',
    firstAscent: '1778 - Lovrenc Willomitzer & team',
    iconEmoji: '🇸🇮',
  },
  {
    id: 'ojos-del-salado',
    name: 'Ojos del Salado',
    elevation: 6893,
    elevationFt: 22615,
    latitude: -27.1094,
    longitude: -68.5414,
    country: 'Chile / Argentina',
    range: 'Andes',
    category: 'andes',
    difficulty: 'Hard',
    description: 'The highest volcano in the world and second highest peak in the Andes. Located in the Atacama Desert, one of the driest places on Earth.',
    firstAscent: '1937 - Jan Alfred Szczepański & Justyn Wojsznis',
    iconEmoji: '🌵',
    routes: ['Normal Route (Chilean side)', 'Argentine Route'],
    camps: [
      { name: 'Refugio Atacama', elevation: 5200 },
      { name: 'Refugio Tejos', elevation: 5825 },
      { name: 'Refugio César', elevation: 6400 },
    ],
  },
  {
    id: 'huascaran',
    name: 'Huascarán',
    elevation: 6768,
    elevationFt: 22205,
    latitude: -9.1222,
    longitude: -77.6042,
    country: 'Peru',
    range: 'Cordillera Blanca',
    category: 'andes',
    difficulty: 'Hard',
    description: 'The highest peak in Peru and the tropics. Located in Huascarán National Park, a UNESCO World Heritage Site.',
    firstAscent: '1932 - German-Austrian expedition',
    iconEmoji: '🦙',
    routes: ['Normal Route (Garganta)', 'Shield Route'],
    camps: [
      { name: 'Base Camp / Musho', elevation: 4450 },
      { name: 'Camp I / Moraine', elevation: 4950 },
      { name: 'Camp II / Garganta', elevation: 5900 },
    ],
  },
  {
    id: 'chimborazo',
    name: 'Chimborazo',
    elevation: 6263,
    elevationFt: 20549,
    latitude: -1.4692,
    longitude: -78.8167,
    country: 'Ecuador',
    range: 'Andes',
    category: 'andes',
    difficulty: 'Hard',
    description: 'While not the highest by elevation, its summit is the farthest point from Earth\'s center due to the equatorial bulge. A massive stratovolcano.',
    firstAscent: '1880 - Edward Whymper & team',
    iconEmoji: '🌍',
    routes: ['Normal Route', 'Whymper Route'],
    camps: [
      { name: 'Carrel Refuge', elevation: 4850 },
      { name: 'Whymper Refuge', elevation: 5000 },
    ],
  },
  {
    id: 'cotopaxi',
    name: 'Cotopaxi',
    elevation: 5897,
    elevationFt: 19347,
    latitude: -0.6838,
    longitude: -78.4378,
    country: 'Ecuador',
    range: 'Andes',
    category: 'andes',
    difficulty: 'Moderate',
    description: 'One of the highest active volcanoes in the world. Its symmetrical cone is covered with glaciers, creating a stunning visual. Popular mountaineering destination.',
    firstAscent: '1872 - Wilhelm Reiss & Ángel Escobar',
    iconEmoji: '🌊',
    routes: ['Normal Route'],
    camps: [
      { name: 'José Ribas Refuge', elevation: 4864 },
    ],
  },
  {
    id: 'illimani',
    name: 'Illimani',
    elevation: 6438,
    elevationFt: 21122,
    latitude: -16.6533,
    longitude: -67.7833,
    country: 'Bolivia',
    range: 'Cordillera Real',
    category: 'andes',
    difficulty: 'Hard',
    description: 'The guardian mountain of La Paz, Bolivia. Its four peaks are visible from the city and it holds spiritual significance for the Aymara people.',
    firstAscent: '1898 - Martin Conway & team',
    iconEmoji: '🏙️',
    routes: ['Normal Route (South Face)', 'Southwest Ridge'],
    camps: [
      { name: 'Base Camp / Puente Roto', elevation: 4450 },
      { name: 'Nido de Cóndores', elevation: 5450 },
      { name: 'High Camp', elevation: 5600 },
    ],
  },
  {
    id: 'huayna-potosi',
    name: 'Huayna Potosí',
    elevation: 6088,
    elevationFt: 19974,
    latitude: -16.2667,
    longitude: -68.1500,
    country: 'Bolivia',
    range: 'Cordillera Real',
    category: 'andes',
    difficulty: 'Moderate',
    description: 'Known as the "easiest 6000m peak in the world." Popular for its accessibility from La Paz and spectacular glaciated routes.',
    firstAscent: '1919 - German Alpine Club expedition',
    iconEmoji: '🧗',
    routes: ['Normal Route', 'French Route'],
    camps: [
      { name: 'Base Camp / Refugio', elevation: 4750 },
      { name: 'Campo Alto / High Camp', elevation: 5300 },
      { name: 'Campo Argentino', elevation: 5500 },
    ],
  },
  {
    id: 'alpamayo',
    name: 'Alpamayo',
    elevation: 5947,
    elevationFt: 19511,
    latitude: -8.8792,
    longitude: -77.6536,
    country: 'Peru',
    range: 'Cordillera Blanca',
    category: 'andes',
    difficulty: 'Hard',
    description: 'Once voted the "Most Beautiful Mountain in the World." Its near-perfect ice pyramid shape and steep fluted ice faces make it an iconic climb.',
    firstAscent: '1957 - German expedition',
    iconEmoji: '💠',
    routes: ['Ferrari Route', 'French Direct'],
    camps: [
      { name: 'Base Camp', elevation: 4300 },
      { name: 'Moraine Camp', elevation: 4900 },
      { name: 'High Camp / Col', elevation: 5400 },
    ],
  },
  {
    id: 'fitz-roy',
    name: 'Fitz Roy',
    elevation: 3405,
    elevationFt: 11171,
    latitude: -49.2714,
    longitude: -73.0436,
    country: 'Argentina',
    range: 'Patagonian Andes',
    category: 'andes',
    difficulty: 'Extreme',
    description: 'One of the most technically challenging mountains in the world. Its sheer granite walls and extreme weather make it a test piece for elite alpinists. The Patagonia brand logo.',
    firstAscent: '1952 - Lionel Terray & Guido Magnone',
    iconEmoji: '🌪️',
    routes: ['Franco-Argentine Route', 'Supercanaleta'],
    camps: [
      { name: 'Paso Superior area', elevation: 2200 },
    ],
  },
  {
    id: 'cerro-torre',
    name: 'Cerro Torre',
    elevation: 3128,
    elevationFt: 10262,
    latitude: -49.2958,
    longitude: -73.1058,
    country: 'Argentina',
    range: 'Patagonian Andes',
    category: 'andes',
    difficulty: 'Extreme',
    description: 'A needle of granite and ice in Patagonia, considered one of the most difficult climbs on Earth. Infamous for constant gale-force winds and ice mushrooms.',
    firstAscent: '1974 - Casimiro Ferrari & team',
    iconEmoji: '🪡',
    routes: ['Compressor Route', 'Ragni Route'],
    camps: [
      { name: 'Nipo Nino area', elevation: 1500 },
    ],
  },
  {
    id: 'sajama',
    name: 'Sajama',
    elevation: 6542,
    elevationFt: 21463,
    latitude: -18.1050,
    longitude: -68.8833,
    country: 'Bolivia',
    range: 'Western Cordillera',
    category: 'andes',
    difficulty: 'Hard',
    description: 'The highest peak in Bolivia and a symmetrical stratovolcano. Located in Sajama National Park with hot springs at its base.',
    firstAscent: '1939 - Wilfrid Kühm & Josef Prem',
    iconEmoji: '♨️',
    routes: ['Standard Route (Southwest Ridge)', 'Normal Route (West Ridge)'],
    camps: [
      { name: 'Base Camp', elevation: 4800 },
      { name: 'High Camp', elevation: 5700 },
    ],
  },
  {
    id: 'volcan-lanin',
    name: 'Volcán Lanín',
    elevation: 3776,
    elevationFt: 12388,
    latitude: -39.6369,
    longitude: -71.5019,
    country: 'Argentina / Chile',
    range: 'Patagonian Andes',
    category: 'andes',
    difficulty: 'Moderate',
    description: 'A perfectly cone-shaped stratovolcano on the Argentina-Chile border. The glaciated summit and volcanic landscape make it a rewarding climb.',
    firstAscent: '1897 - Survey team',
    iconEmoji: '🏔️',
  },
  {
    id: 'mercedario',
    name: 'Mercedario',
    elevation: 6720,
    elevationFt: 22047,
    latitude: -31.9800,
    longitude: -70.1133,
    country: 'Argentina',
    range: 'Andes',
    category: 'andes',
    difficulty: 'Hard',
    description: 'The seventh highest peak in the Andes. A remote and less-visited peak offering solitude compared to nearby Aconcagua.',
    firstAscent: '1934 - Adam Karpiński & team',
    iconEmoji: '🏜️',
    routes: ['Normal Route (Southwest Ridge)', 'North Ridge'],
    camps: [
      { name: 'Base Camp', elevation: 5080 },
      { name: 'High Camp', elevation: 5600 },
    ],
  },
  {
    id: 'ama-dablam',
    name: 'Ama Dablam',
    elevation: 6812,
    elevationFt: 22349,
    latitude: 27.8614,
    longitude: 86.8611,
    country: 'Nepal',
    range: 'Himalaya',
    category: 'himalaya',
    difficulty: 'Hard',
    description: 'Known as the "Matterhorn of the Himalaya" for its striking shape. One of the most beautiful and popular climbing peaks in Nepal.',
    firstAscent: '1961 - Mike Gill, Barry Bishop & team',
    iconEmoji: '💍',
    routes: ['Southwest Ridge'],
    camps: [
      { name: 'Base Camp', elevation: 4570 },
      { name: 'Camp I', elevation: 5340 },
      { name: 'Camp II', elevation: 5910 },
      { name: 'Camp III', elevation: 6350 },
    ],
  },
  {
    id: 'island-peak',
    name: 'Island Peak (Imja Tse)',
    elevation: 6189,
    elevationFt: 20305,
    latitude: 27.9261,
    longitude: 86.9333,
    country: 'Nepal',
    range: 'Himalaya',
    category: 'himalaya',
    difficulty: 'Moderate',
    description: 'One of the most popular trekking peaks in Nepal. Named for its island-like appearance when viewed from Dingboche. Often combined with Everest Base Camp trek.',
    firstAscent: '1956 - Tenzing Norgay & team',
    iconEmoji: '🏝️',
    routes: ['Normal Route (South Ridge)', 'North Ridge'],
    camps: [
      { name: 'Base Camp / Pareshaya Gyab', elevation: 5080 },
      { name: 'High Camp', elevation: 5600 },
    ],
  },
  {
    id: 'mera-peak',
    name: 'Mera Peak',
    elevation: 6476,
    elevationFt: 21247,
    latitude: 27.7500,
    longitude: 86.8667,
    country: 'Nepal',
    range: 'Himalaya',
    category: 'himalaya',
    difficulty: 'Moderate',
    description: 'The highest trekking peak in Nepal. Offers stunning panoramic views of five 8000m peaks from its summit.',
    firstAscent: '1953 - Jimmy Roberts & Sen Tenzing',
    iconEmoji: '👁️',
    routes: ['Standard Route (North Face)'],
    camps: [
      { name: 'Mera La', elevation: 5415 },
      { name: 'High Camp', elevation: 5800 },
    ],
  },
  {
    id: 'pumori',
    name: 'Pumori',
    elevation: 7161,
    elevationFt: 23494,
    latitude: 28.0125,
    longitude: 86.8250,
    country: 'Nepal / China',
    range: 'Himalaya',
    category: 'himalaya',
    difficulty: 'Hard',
    description: 'Known as "Everest\'s Daughter" and visible from Everest Base Camp. Its southeast face provides a stunning backdrop to the Khumbu region.',
    firstAscent: '1962 - Gerhard Lenser',
    iconEmoji: '👧',
    routes: ['Normal Route (Southeast Ridge)', 'Southwest Face'],
    camps: [
      { name: 'Base Camp', elevation: 5300 },
      { name: 'Camp I', elevation: 5650 },
      { name: 'Camp II', elevation: 6100 },
    ],
  },
  {
    id: 'baruntse',
    name: 'Baruntse',
    elevation: 7129,
    elevationFt: 23389,
    latitude: 27.8681,
    longitude: 86.9806,
    country: 'Nepal',
    range: 'Himalaya',
    category: 'himalaya',
    difficulty: 'Hard',
    description: 'A striking peak between the Barun and Imja valleys. A demanding expedition peak that offers true high-altitude mountaineering experience.',
    firstAscent: '1954 - Colin Todd & team',
    iconEmoji: '🏕️',
    routes: ['South Ridge', 'East Ridge'],
    camps: [
      { name: 'Base Camp', elevation: 5300 },
      { name: 'Camp I', elevation: 6000 },
    ],
  },
  {
    id: 'lobuche-east',
    name: 'Lobuche East',
    elevation: 6119,
    elevationFt: 20075,
    latitude: 27.9556,
    longitude: 86.7944,
    country: 'Nepal',
    range: 'Himalaya',
    category: 'himalaya',
    difficulty: 'Moderate',
    description: 'A popular trekking peak near Everest Base Camp. The summit offers incredible views of the Khumbu icefall and surrounding giants.',
    firstAscent: '1984 - Various teams',
    iconEmoji: '⛺',
    routes: ['Normal Route (South Ridge)'],
    camps: [
      { name: 'Base Camp', elevation: 4950 },
      { name: 'High Camp', elevation: 5400 },
    ],
  },
  {
    id: 'annapurna-south',
    name: 'Annapurna South',
    elevation: 7219,
    elevationFt: 23684,
    latitude: 28.5275,
    longitude: 83.8025,
    country: 'Nepal',
    range: 'Himalaya',
    category: 'himalaya',
    difficulty: 'Hard',
    description: 'Part of the Annapurna massif. Its dramatic south face dominates the view from the popular Annapurna Base Camp trek.',
    firstAscent: '1964 - Japanese expedition',
    iconEmoji: '🌄',
  },
  {
    id: 'machapuchare',
    name: 'Machapuchare',
    elevation: 6993,
    elevationFt: 22943,
    latitude: 28.5097,
    longitude: 83.9472,
    country: 'Nepal',
    range: 'Himalaya',
    category: 'himalaya',
    difficulty: 'Extreme',
    description: 'The "Fish Tail" mountain, sacred to the god Shiva. Climbing is prohibited by the Nepali government, making it one of the world\'s most famous unclimbed peaks.',
    firstAscent: 'Unclimbed (closed to climbing)',
    iconEmoji: '🐟',
  },
  {
    id: 'tilicho-peak',
    name: 'Tilicho Peak',
    elevation: 7134,
    elevationFt: 23406,
    latitude: 28.6836,
    longitude: 83.7792,
    country: 'Nepal',
    range: 'Himalaya',
    category: 'himalaya',
    difficulty: 'Hard',
    description: 'Overlooking Tilicho Lake, one of the highest lakes in the world. Part of the Annapurna massif with challenging routes on all faces.',
    firstAscent: '1978 - French expedition',
    iconEmoji: '🏞️',
  },
  {
    id: 'mt-rainier',
    name: 'Mount Rainier',
    elevation: 4392,
    elevationFt: 14411,
    latitude: 46.8528,
    longitude: -121.7604,
    country: 'USA (Washington)',
    range: 'Cascades',
    category: 'other',
    difficulty: 'Hard',
    description: 'The most heavily glaciated peak in the contiguous US. A massive active stratovolcano and training ground for bigger Himalayan expeditions.',
    firstAscent: '1870 - Hazard Stevens & Philemon Van Trump',
    iconEmoji: '🌧️',
    routes: ['Disappointment Cleaver', 'Emmons Glacier', 'Kautz Glacier'],
    camps: [
      { name: 'Camp Muir', elevation: 3060 },
      { name: 'Camp Schurman', elevation: 2900 },
      { name: 'Ingraham Flats', elevation: 3300 },
    ],
  },
  {
    id: 'mt-hood',
    name: 'Mount Hood',
    elevation: 3429,
    elevationFt: 11250,
    latitude: 45.3735,
    longitude: -121.6959,
    country: 'USA (Oregon)',
    range: 'Cascades',
    category: 'other',
    difficulty: 'Moderate',
    description: 'Oregon\'s highest peak and most climbed glaciated peak in North America. The south side route is a popular introduction to mountaineering.',
    firstAscent: '1857 - Thomas Dryer & team',
    iconEmoji: '🌲',
    routes: ['South Side / Hogsback', 'Cooper Spur', 'Sunshine Route'],
    camps: [
      { name: 'Timberline Lodge', elevation: 1800 },
      { name: 'Illumination Saddle', elevation: 2830 },
    ],
  },
  {
    id: 'mt-shasta',
    name: 'Mount Shasta',
    elevation: 4322,
    elevationFt: 14179,
    latitude: 41.4092,
    longitude: -122.1949,
    country: 'USA (California)',
    range: 'Cascades',
    category: 'other',
    difficulty: 'Moderate',
    description: 'A massive stratovolcano in Northern California. Known for its spiritual significance and beautiful symmetrical cone visible for over 100 miles.',
    firstAscent: '1854 - Elias Pearce',
    iconEmoji: '✨',
    routes: ['Avalanche Gulch', 'Hotlum Glacier', 'Casaval Ridge'],
    camps: [
      { name: 'Horse Camp', elevation: 2100 },
      { name: 'Lake Helen', elevation: 3170 },
      { name: 'Hidden Valley', elevation: 2800 },
    ],
  },
  {
    id: 'mt-whitney',
    name: 'Mount Whitney',
    elevation: 4421,
    elevationFt: 14505,
    latitude: 36.5785,
    longitude: -118.2923,
    country: 'USA (California)',
    range: 'Sierra Nevada',
    category: 'other',
    difficulty: 'Moderate',
    description: 'The highest peak in the contiguous United States. The Whitney Trail is one of the most popular hikes in America with a highly competitive permit system.',
    firstAscent: '1873 - Charles Begole & team',
    iconEmoji: '🌅',
    routes: ['Whitney Trail', 'Mountaineer\'s Route', 'East Face'],
    camps: [
      { name: 'Outpost Camp', elevation: 3140 },
      { name: 'Trail Camp', elevation: 3660 },
      { name: 'Upper Boy Scout Lake', elevation: 3450 },
    ],
  },
  {
    id: 'mt-fuji',
    name: 'Mount Fuji',
    elevation: 3776,
    elevationFt: 12389,
    latitude: 35.3606,
    longitude: 138.7274,
    country: 'Japan',
    range: 'Independent',
    category: 'other',
    difficulty: 'Easy',
    description: 'Japan\'s highest peak and most iconic symbol. A UNESCO World Heritage Site climbed by over 300,000 people annually during the summer season.',
    firstAscent: '663 AD - En no Ozunu (traditional)',
    iconEmoji: '🗾',
    routes: ['Yoshida Trail', 'Subashiri Trail', 'Gotemba Trail', 'Fujinomiya Trail'],
    camps: [
      { name: '5th Station', elevation: 2305 },
      { name: '8th Station Huts', elevation: 3100 },
      { name: 'Summit Huts', elevation: 3700 },
    ],
  },
  {
    id: 'aoraki',
    name: 'Aoraki / Mount Cook',
    elevation: 3724,
    elevationFt: 12218,
    latitude: -43.5951,
    longitude: 170.1418,
    country: 'New Zealand',
    range: 'Southern Alps',
    category: 'other',
    difficulty: 'Hard',
    description: 'The highest peak in New Zealand. Where Sir Edmund Hillary honed his skills before Everest. Known for extreme weather and avalanche danger.',
    firstAscent: '1894 - Tom Fyfe, George Graham & Jack Clarke',
    iconEmoji: '🥝',
  },
  {
    id: 'mt-kenya',
    name: 'Mount Kenya (Batian)',
    elevation: 5199,
    elevationFt: 17057,
    latitude: -0.1521,
    longitude: 37.3084,
    country: 'Kenya',
    range: 'Eastern Rift Mountains',
    category: 'other',
    difficulty: 'Hard',
    description: 'Africa\'s second highest mountain. Batian is the highest of its jagged summits, requiring technical climbing. A UNESCO World Heritage Site.',
    firstAscent: '1899 - Halford Mackinder & team',
    iconEmoji: '🦁',
  },
  {
    id: 'mt-stanley',
    name: 'Mount Stanley (Margherita Peak)',
    elevation: 5109,
    elevationFt: 16763,
    latitude: 0.3861,
    longitude: 29.8792,
    country: 'Uganda / DR Congo',
    range: 'Rwenzori Mountains',
    category: 'other',
    difficulty: 'Hard',
    description: 'The third highest peak in Africa, located in the "Mountains of the Moon." Known for its otherworldly vegetation and frequent cloud cover.',
    firstAscent: '1906 - Luigi di Savoia & team',
    iconEmoji: '🌙',
  },
  {
    id: 'toubkal',
    name: 'Jebel Toubkal',
    elevation: 4167,
    elevationFt: 13671,
    latitude: 31.0597,
    longitude: -7.9153,
    country: 'Morocco',
    range: 'Atlas Mountains',
    category: 'other',
    difficulty: 'Moderate',
    description: 'The highest peak in North Africa and the Arab world. A popular trekking destination accessible from Marrakech, offering Sahara views from the summit.',
    firstAscent: '1923 - Marquis de Segonzac & team',
    iconEmoji: '🐪',
  },
  {
    id: 'mt-olympus',
    name: 'Mount Olympus (Mytikas)',
    elevation: 2918,
    elevationFt: 9573,
    latitude: 40.0859,
    longitude: 22.3583,
    country: 'Greece',
    range: 'Olympus Range',
    category: 'other',
    difficulty: 'Moderate',
    description: 'Home of the Greek gods in mythology. The highest peak in Greece with Mytikas requiring an exposed scramble. A UNESCO Biosphere Reserve.',
    firstAscent: '1913 - Christos Kakkalos & team',
    iconEmoji: '⚡',
  },
  {
    id: 'ben-nevis',
    name: 'Ben Nevis',
    elevation: 1345,
    elevationFt: 4413,
    latitude: 56.7969,
    longitude: -5.0036,
    country: 'United Kingdom',
    range: 'Grampian Mountains',
    category: 'other',
    difficulty: 'Easy',
    description: 'The highest peak in the British Isles. The tourist path is a popular hillwalk, while the North Face offers world-class winter climbing.',
    firstAscent: '1771 - James Robertson',
    iconEmoji: '🏴',
  },
  {
    id: 'mt-elbrus-west',
    name: 'Mount Ararat',
    elevation: 5137,
    elevationFt: 16854,
    latitude: 39.7019,
    longitude: 44.2983,
    country: 'Turkey',
    range: 'Armenian Highlands',
    category: 'other',
    difficulty: 'Moderate',
    description: 'The legendary resting place of Noah\'s Ark. Turkey\'s highest peak, a snow-capped dormant volcano with enormous prominence visible for hundreds of miles.',
    firstAscent: '1829 - Friedrich Parrot',
    iconEmoji: '🕊️',
  },
  {
    id: 'mt-kinabalu',
    name: 'Mount Kinabalu',
    elevation: 4095,
    elevationFt: 13435,
    latitude: 6.0753,
    longitude: 116.5584,
    country: 'Malaysia',
    range: 'Crocker Range',
    category: 'other',
    difficulty: 'Moderate',
    description: 'The highest peak in Southeast Asia (Borneo). A UNESCO World Heritage Site known for incredible biodiversity and the famous Via Ferrata.',
    firstAscent: '1851 - Hugh Low & team',
    iconEmoji: '🌺',
  },
  {
    id: 'orizaba',
    name: 'Pico de Orizaba',
    elevation: 5636,
    elevationFt: 18491,
    latitude: 19.0300,
    longitude: -97.2683,
    country: 'Mexico',
    range: 'Trans-Mexican Volcanic Belt',
    category: 'other',
    difficulty: 'Moderate',
    description: 'The highest peak in Mexico and third highest in North America. A glaciated stratovolcano offering a non-technical but demanding climb.',
    firstAscent: '1848 - F. Maynard & William Reynolds',
    iconEmoji: '🇲🇽',
  },
  {
    id: 'iztaccihuatl',
    name: 'Iztaccíhuatl',
    elevation: 5230,
    elevationFt: 17160,
    latitude: 19.1789,
    longitude: -98.6422,
    country: 'Mexico',
    range: 'Trans-Mexican Volcanic Belt',
    category: 'other',
    difficulty: 'Moderate',
    description: 'Known as the "Sleeping Woman" from its silhouette. Mexico\'s third highest peak, offering a popular training climb near Mexico City.',
    firstAscent: '1889 - James de Salis',
    iconEmoji: '😴',
  },
  {
    id: 'mt-cook',
    name: 'Mount Aspiring',
    elevation: 3033,
    elevationFt: 9951,
    latitude: -44.3833,
    longitude: 168.7333,
    country: 'New Zealand',
    range: 'Southern Alps',
    category: 'other',
    difficulty: 'Hard',
    description: 'Known as the "Matterhorn of the South" for its pyramidal shape. A challenging technical climb in Mount Aspiring National Park.',
    firstAscent: '1909 - Jack Clarke & team',
    iconEmoji: '🐑',
  },
  {
    id: 'mt-blanc-du-tacul',
    name: 'Mont Blanc du Tacul',
    elevation: 4248,
    elevationFt: 13937,
    latitude: 45.8558,
    longitude: 6.8833,
    country: 'France',
    range: 'Mont Blanc Massif',
    category: 'alps',
    difficulty: 'Hard',
    description: 'Often climbed as part of the Mont Blanc three-summit traverse. The Aiguille du Midi cable car provides access to this glaciated peak.',
    firstAscent: '1855 - H.D. Speer & team',
    iconEmoji: '🚠',
  },
  {
    id: 'lyskamm',
    name: 'Lyskamm',
    elevation: 4527,
    elevationFt: 14852,
    latitude: 45.9275,
    longitude: 7.8308,
    country: 'Switzerland / Italy',
    range: 'Pennine Alps',
    category: 'alps',
    difficulty: 'Hard',
    description: 'Known as "Menschenfresser" (Man-eater) due to avalanches and cornices on its exposed ridge. A beautiful but dangerous traverse in the Monte Rosa area.',
    firstAscent: '1861 - Various teams',
    iconEmoji: '☠️',
  },
  {
    id: 'mt-temple',
    name: 'Mount Temple',
    elevation: 3544,
    elevationFt: 11627,
    latitude: 51.3500,
    longitude: -116.2000,
    country: 'Canada',
    range: 'Canadian Rockies',
    category: 'other',
    difficulty: 'Moderate',
    description: 'The highest peak in the Lake Louise area of Banff National Park. A popular scramble with stunning views of the surrounding Canadian Rockies.',
    firstAscent: '1894 - Walter Wilcox & team',
    iconEmoji: '🍁',
  },
  {
    id: 'mt-robson',
    name: 'Mount Robson',
    elevation: 3954,
    elevationFt: 12972,
    latitude: 53.1117,
    longitude: -119.1553,
    country: 'Canada',
    range: 'Canadian Rockies',
    category: 'other',
    difficulty: 'Hard',
    description: 'The highest peak in the Canadian Rockies. Known as the "Monarch of the Canadian Rockies" and infamous for terrible weather and low success rates.',
    firstAscent: '1913 - Conrad Kain & team',
    iconEmoji: '🦌',
  },
  {
    id: 'mt-logan',
    name: 'Mount Logan',
    elevation: 5959,
    elevationFt: 19551,
    latitude: 60.5670,
    longitude: -140.4055,
    country: 'Canada',
    range: 'Saint Elias Mountains',
    category: 'other',
    difficulty: 'Hard',
    description: 'The highest peak in Canada and second highest in North America. Has the largest base circumference of any non-volcanic mountain on Earth.',
    firstAscent: '1925 - Albert MacCarthy & team',
    iconEmoji: '🇨🇦',
  },
  {
    id: 'mt-elbrus-traverse',
    name: 'Damavand',
    elevation: 5610,
    elevationFt: 18406,
    latitude: 35.9515,
    longitude: 52.1091,
    country: 'Iran',
    range: 'Alborz',
    category: 'other',
    difficulty: 'Moderate',
    description: 'The highest peak in Iran and the Middle East. A massive stratovolcano with sulfurous fumaroles near its summit. A holy mountain in Persian mythology.',
    firstAscent: '1837 - W.T. Thomson',
    iconEmoji: '🔥',
  },
  {
    id: 'musala',
    name: 'Musala',
    elevation: 2925,
    elevationFt: 9596,
    latitude: 42.1792,
    longitude: 23.5853,
    country: 'Bulgaria',
    range: 'Rila Mountains',
    category: 'other',
    difficulty: 'Easy',
    description: 'The highest peak in the Balkans and Bulgaria. A popular hiking destination in Rila National Park with chairlift access.',
    firstAscent: 'Unknown (ancient)',
    iconEmoji: '🌿',
  },
  {
    id: 'gerlachovsky',
    name: 'Gerlachovský štít',
    elevation: 2655,
    elevationFt: 8711,
    latitude: 49.1644,
    longitude: 20.1342,
    country: 'Slovakia',
    range: 'Tatra Mountains',
    category: 'other',
    difficulty: 'Moderate',
    description: 'The highest peak in the Carpathian Mountains and Slovakia. Climbing requires a licensed mountain guide due to its protected status.',
    firstAscent: '1834 - Ján Still & team',
    iconEmoji: '🐺',
  },
  {
    id: 'mt-blanc-chamomix',
    name: 'Aiguille du Midi',
    elevation: 3842,
    elevationFt: 12605,
    latitude: 45.8794,
    longitude: 6.8872,
    country: 'France',
    range: 'Mont Blanc Massif',
    category: 'alps',
    difficulty: 'Hard',
    description: 'A famous granite needle in the Mont Blanc massif. Home to the highest cable car in the Alps and the starting point for the classic Vallée Blanche descent.',
    firstAscent: '1818 - Various teams',
    iconEmoji: '🗼',
  },
  {
    id: 'mt-baker',
    name: 'Mount Baker',
    elevation: 3286,
    elevationFt: 10781,
    latitude: 48.7768,
    longitude: -121.8145,
    country: 'USA (Washington)',
    range: 'Cascades',
    category: 'other',
    difficulty: 'Moderate',
    description: 'The most heavily glaciated volcano in the Cascades after Rainier. Holds the world record for most snowfall in a single season (1140 inches in 1998-99).',
    firstAscent: '1868 - Edmund Coleman & team',
    iconEmoji: '🌨️',
  },
  {
    id: 'volcano-teide',
    name: 'Mount Teide',
    elevation: 3718,
    elevationFt: 12198,
    latitude: 28.2724,
    longitude: -16.6425,
    country: 'Spain (Canary Islands)',
    range: 'Tenerife',
    category: 'other',
    difficulty: 'Easy',
    description: 'Spain\'s highest peak and the highest point in the Atlantic islands. A UNESCO World Heritage Site and active stratovolcano.',
    firstAscent: '1582 - Sir Edmund Scory',
    iconEmoji: '🏖️',
  },
  {
    id: 'cascade-14er-1',
    name: 'Mount Evans',
    elevation: 4348,
    elevationFt: 14265,
    latitude: 39.5883,
    longitude: -105.6438,
    country: 'USA (Colorado)',
    range: 'Front Range',
    category: '14ers',
    difficulty: 'Easy',
    description: 'Home to the highest paved road in North America. The summit offers panoramic views of the Continental Divide. A mountain goat haven.',
    firstAscent: '1863 - Survey team',
    iconEmoji: '🐐',
  },
  {
    id: 'mt-bierstadt',
    name: 'Mount Bierstadt',
    elevation: 4287,
    elevationFt: 14065,
    latitude: 39.5828,
    longitude: -105.6686,
    country: 'USA (Colorado)',
    range: 'Front Range',
    category: '14ers',
    difficulty: 'Easy',
    description: 'One of the most popular 14ers due to its short approach and moderate difficulty. Named after painter Albert Bierstadt who captured the landscape.',
    firstAscent: '1863 - Survey team',
    iconEmoji: '🎨',
  },
  {
    id: 'mt-sneffels',
    name: 'Mount Sneffels',
    elevation: 4315,
    elevationFt: 14158,
    latitude: 38.0036,
    longitude: -107.7922,
    country: 'USA (Colorado)',
    range: 'San Juan Mountains',
    category: '14ers',
    difficulty: 'Hard',
    description: 'One of Colorado\'s most photogenic peaks. Named after the volcano in Jules Verne\'s "Journey to the Center of the Earth."',
    firstAscent: '1874 - Survey team',
    iconEmoji: '📖',
  },
  {
    id: 'iliniza-sur',
    name: 'Iliniza Sur',
    elevation: 5248,
    elevationFt: 17218,
    latitude: -0.6597,
    longitude: -78.6847,
    country: 'Ecuador',
    range: 'Andes',
    category: 'andes',
    difficulty: 'Hard',
    description: 'The higher of the twin Iliniza peaks. A technically demanding glacier climb requiring ice axes and crampons, with crevasse dangers and unpredictable weather near the equator.',
    firstAscent: '1880 - Jean-Antoine Carrel & Edward Whymper',
    iconEmoji: '🧊',
  },
  {
    id: 'cayambe',
    name: 'Cayambe',
    elevation: 5790,
    elevationFt: 18996,
    latitude: 0.0292,
    longitude: -77.9864,
    country: 'Ecuador',
    range: 'Andes',
    category: 'andes',
    difficulty: 'Hard',
    description: 'The third highest peak in Ecuador and the highest point in the world directly on the equator. A glaciated stratovolcano with crevasse-riddled slopes and unpredictable weather.',
    firstAscent: '1880 - Edward Whymper & Jean-Antoine Carrel',
    iconEmoji: '🌐',
  },
  {
    id: 'lenin-peak',
    name: 'Lenin Peak',
    elevation: 7134,
    elevationFt: 23406,
    latitude: 39.9461,
    longitude: 72.8781,
    country: 'Kyrgyzstan / Tajikistan',
    range: 'Pamir Mountains',
    category: 'other',
    difficulty: 'Hard',
    description: 'One of the easiest 7000m peaks in the world and a popular first high-altitude expedition. Located in the Trans-Alay Range of the Pamirs, it offers a non-technical but demanding climb with extreme altitude and weather.',
    firstAscent: '1928 - Karl Wien, Eugene Allwein & Erwin Schneider',
    iconEmoji: '⭐',
  },
  {
    id: 'iliniza-norte',
    name: 'Iliniza Norte',
    elevation: 5126,
    elevationFt: 16818,
    latitude: -0.6558,
    longitude: -78.6978,
    country: 'Ecuador',
    range: 'Andes',
    category: 'andes',
    difficulty: 'Moderate',
    description: 'The lower of the twin Iliniza peaks. A popular acclimatization climb before attempting higher Ecuadorian volcanoes like Cotopaxi or Chimborazo. The route is non-glaciated but involves scrambling on loose rock.',
    firstAscent: '1912 - Nicolás Martínez',
    iconEmoji: '🌫️',
  },
  {
    id: 'meru-sharks-fin',
    name: 'Meru (Shark\'s Fin)',
    elevation: 6660,
    elevationFt: 21850,
    latitude: 30.8667,
    longitude: 79.0333,
    country: 'India',
    range: 'Garhwal Himalaya',
    category: 'himalaya',
    difficulty: 'Extreme',
    description: 'One of the most coveted prizes in alpinism. The Shark\'s Fin route on Meru\'s central peak is a 1,500m granite wall at extreme altitude, combining big-wall rock climbing, ice, and mixed terrain. Famously climbed by Conrad Anker, Jimmy Chin, and Renan Ozturk in 2011.',
    firstAscent: '2011 - Conrad Anker, Jimmy Chin & Renan Ozturk (Shark\'s Fin)',
    iconEmoji: '🦈',
  },
  {
    id: 'shivling',
    name: 'Shivling',
    elevation: 6543,
    elevationFt: 21467,
    latitude: 30.8700,
    longitude: 79.0650,
    country: 'India',
    range: 'Garhwal Himalaya',
    category: 'himalaya',
    difficulty: 'Very Difficult',
    description: 'A stunning pyramidal peak near Tapovan in the Garhwal Himalaya, considered one of the most beautiful mountains in the world. Its name means "Shiva\'s Lingam" and its near-perfect geometry has attracted elite alpinists since its first ascent.',
    firstAscent: '1974 - Indian-Tibetan Border Police expedition',
    iconEmoji: '🔱',
  },
  {
    id: 'aiguille-du-dru',
    name: 'Aiguille du Dru',
    elevation: 3754,
    elevationFt: 12316,
    latitude: 45.9333,
    longitude: 6.9500,
    country: 'France',
    range: 'Mont Blanc Massif',
    category: 'alps',
    difficulty: 'Very Difficult',
    description: 'A dramatic granite needle in the Mont Blanc massif, towering above Chamonix. The Dru is one of the great alpine north faces and a testpiece for rock climbers. A massive rockfall in 2005 destroyed the famous Bonatti Pillar route.',
    firstAscent: '1878 - Clinton Dent, J. Walker Hartley, Alexander Burgener & Kaspar Maurer',
    iconEmoji: '🗼',
  },
  {
    id: 'piz-badile',
    name: 'Piz Badile',
    elevation: 3308,
    elevationFt: 10853,
    latitude: 46.2942,
    longitude: 9.6139,
    country: 'Switzerland / Italy',
    range: 'Bregaglia Alps',
    category: 'alps',
    difficulty: 'Difficult',
    description: 'A magnificent granite peak straddling the Swiss-Italian border with one of the finest north faces in the Alps. The Cassin Route on the northeast face is a classic of alpine rock climbing, first climbed by Riccardo Cassin in 1937.',
    firstAscent: '1867 - W.A.B. Coolidge, F.F. Tuckett, with Christian Almer & François Devouassoud',
    iconEmoji: '🧗',
  },
  {
    id: 'mt-hunter',
    name: 'Mount Hunter',
    elevation: 4442,
    elevationFt: 14573,
    latitude: 62.9500,
    longitude: -151.0833,
    country: 'USA',
    range: 'Alaska Range',
    category: 'other',
    difficulty: 'Very Difficult',
    description: 'Known as Begguya (Denali\'s Child) in Dena\'ina, this massive Alaskan peak rises near Denali with enormous vertical relief. Its steep faces and ridges, combined with subarctic weather, make it one of the most challenging climbs in North America.',
    firstAscent: '1954 - Fred Beckey, Heinrich Harrer & Henry Meybohm',
    iconEmoji: '🏔️',
  },
  {
    id: 'mt-waddington',
    name: 'Mount Waddington',
    elevation: 4019,
    elevationFt: 13186,
    latitude: 51.3833,
    longitude: -125.2833,
    country: 'Canada',
    range: 'Coast Mountains',
    category: 'other',
    difficulty: 'Very Difficult',
    description: 'The highest peak entirely within British Columbia, known as the "Mystery Mountain" for its remote and inaccessible location. Extremely challenging due to notoriously bad weather, heavy glaciation, and difficult rock. It repelled 16 attempts before Fritz Wiessner and Bill House summited in 1936.',
    firstAscent: '1936 - Fritz Wiessner & Bill House',
    iconEmoji: '🌲',
  },
  {
    id: 'torres-del-paine',
    name: 'Torres del Paine (Central Tower)',
    elevation: 2850,
    elevationFt: 9350,
    latitude: -50.9423,
    longitude: -72.9697,
    country: 'Chile',
    range: 'Paine Massif',
    category: 'andes',
    difficulty: 'Very Difficult',
    description: 'The iconic Central Tower of the Torres del Paine is a sheer granite monolith rising above glacial lakes in Patagonia. One of the most photographed peaks in South America, it demands technical rock climbing and is a bucket-list objective for alpinists worldwide.',
    firstAscent: '1963 - Chris Bonington & Don Whillans',
    iconEmoji: '🗿',
  },
  {
    id: 'paine-grande',
    name: 'Paine Grande',
    elevation: 3050,
    elevationFt: 10007,
    latitude: -50.9833,
    longitude: -73.0833,
    country: 'Chile',
    range: 'Paine Massif',
    category: 'andes',
    difficulty: 'Hard',
    description: 'The highest peak in the Torres del Paine massif, Paine Grande is a massive, heavily glaciated mountain with dramatic hanging glaciers and unpredictable Patagonian weather. Its broad summit towers over Grey Glacier and the surrounding steppe.',
    firstAscent: '1957 - Italian expedition led by Clemente Maffei',
    iconEmoji: '🧊',
  },
  {
    id: 'nuptse',
    name: 'Nuptse',
    elevation: 7861,
    elevationFt: 25791,
    latitude: 27.9653,
    longitude: 86.8947,
    country: 'Nepal',
    range: 'Himalaya',
    category: 'himalaya',
    difficulty: 'Very Difficult',
    description: 'Nuptse means "West Peak" in Tibetan and forms the massive south wall of the Everest amphitheater. Its imposing 2-mile-long ridge and sheer south face make it one of the most dramatic sights in the Khumbu. Despite being overshadowed by Everest and Lhotse, it is a formidable climb in its own right.',
    firstAscent: '1961 - Dennis Davis & Tashi Sherpa (British expedition)',
    iconEmoji: '🏔️',
  },
  {
    id: 'rakaposhi',
    name: 'Rakaposhi',
    elevation: 7788,
    elevationFt: 25551,
    latitude: 36.1478,
    longitude: 74.5250,
    country: 'Pakistan',
    range: 'Karakoram',
    category: 'himalaya',
    difficulty: 'Very Difficult',
    description: 'One of the most visually stunning mountains in the world, rising over 5,800m directly from the Hunza Valley floor — one of the greatest elevation gains from base to summit on Earth. Its name means "shining wall" in the local Burushaski language.',
    firstAscent: '1958 - Mike Banks & Tom Patey (British-Pakistani expedition)',
    iconEmoji: '✨',
  },
  {
    id: 'khan-tengri',
    name: 'Khan Tengri',
    elevation: 7010,
    elevationFt: 22999,
    latitude: 42.2133,
    longitude: 80.1764,
    country: 'Kazakhstan / Kyrgyzstan',
    range: 'Tian Shan',
    category: 'other',
    difficulty: 'Hard',
    description: 'The "Lord of the Spirits" is a perfect marble pyramid and the northernmost 7000m peak in the world. Famous for glowing pink and red at sunset due to its marble rock composition. One of the most beautiful and coveted peaks in Central Asia.',
    firstAscent: '1931 - Mikhail Pogrebetsky & team',
    iconEmoji: '💎',
  },
  {
    id: 'pobeda-peak',
    name: 'Pobeda Peak (Jengish Chokusu)',
    elevation: 7439,
    elevationFt: 24406,
    latitude: 42.0339,
    longitude: 80.1253,
    country: 'Kyrgyzstan / China',
    range: 'Tian Shan',
    category: 'other',
    difficulty: 'Very Difficult',
    description: 'The highest peak in the Tian Shan and one of the most dangerous 7000m peaks due to its remote location, extreme cold, and violent storms. Its long summit ridge and massive glaciated flanks have claimed many lives. Often climbed together with nearby Khan Tengri.',
    firstAscent: '1956 - Vitaly Abalakov & team (Soviet expedition)',
    iconEmoji: '🌬️',
  },
  {
    id: 'popocatepetl',
    name: 'Popocatépetl',
    elevation: 5426,
    elevationFt: 17802,
    latitude: 19.0225,
    longitude: -98.6278,
    country: 'Mexico',
    range: 'Trans-Mexican Volcanic Belt',
    category: 'other',
    difficulty: 'Moderate',
    description: 'Mexico\'s second highest peak and one of the most active volcanoes in North America. Its name means "Smoking Mountain" in Nahuatl. The snow-capped stratovolcano towers over Mexico City and Puebla, and is steeped in Aztec mythology alongside neighboring Iztaccíhuatl.',
    firstAscent: '1519 - Diego de Ordaz (Spanish conquistador)',
    iconEmoji: '🌋',
  },
  {
    id: 'mt-st-helens',
    name: 'Mount St. Helens',
    elevation: 2549,
    elevationFt: 8363,
    latitude: 46.1912,
    longitude: -122.1944,
    country: 'USA (Washington)',
    range: 'Cascades',
    category: 'other',
    difficulty: 'Moderate',
    description: 'Famous for its catastrophic 1980 eruption that blew off the entire north face, reducing its height by over 1,300 feet. The horseshoe-shaped crater and surrounding blast zone remain a dramatic testament to volcanic power. Now a National Volcanic Monument and popular climb with a permit system.',
    firstAscent: '1853 - Thomas J. Dryer',
    iconEmoji: '💨',
  },
  {
    id: 'grand-teton',
    name: 'Grand Teton',
    elevation: 4199,
    elevationFt: 13775,
    latitude: 43.7412,
    longitude: -110.8024,
    country: 'USA',
    range: 'Teton Range',
    category: 'other',
    difficulty: 'Moderate-Difficult',
    description: 'The highest peak in the Teton Range, rising dramatically from the Snake River Plain in Wyoming. An iconic American peak with the classic Owen-Spalding and Exum Ridge routes. Its striking cathedral-like spire makes it one of the most photographed mountains in North America.',
    firstAscent: '1898 - William Owen, Franklin Spalding, John Shive & Frank Petersen',
    iconEmoji: '⛰️',
  },
  {
    id: 'tre-cime',
    name: 'Tre Cime di Lavaredo',
    elevation: 2999,
    elevationFt: 9839,
    latitude: 46.6184,
    longitude: 12.3031,
    country: 'Italy',
    range: 'Dolomites',
    category: 'alps',
    difficulty: 'Moderate-Difficult',
    description: 'One of the most iconic rock formations in the Alps — three dramatic vertical pillars rising side by side from a high alpine plateau. The north faces are sheer 500m walls that became legendary testing grounds for Dolomite climbers. A UNESCO World Heritage Site and symbol of the Dolomites.',
    firstAscent: '1869 - Paul Grohmann (Cima Grande)',
    iconEmoji: '🪨',
  },
  {
    id: 'mt-meru-tanzania',
    name: 'Mount Meru',
    elevation: 4566,
    elevationFt: 14980,
    latitude: -3.2459,
    longitude: 36.7520,
    country: 'Tanzania',
    range: 'Eastern Rift Mountains',
    category: 'other',
    difficulty: 'Moderate',
    description: 'The fifth highest mountain in Africa and the second highest in Tanzania after Kilimanjaro. A massive stratovolcano with a dramatic horseshoe-shaped crater formed by a catastrophic collapse. Often used as an acclimatization climb before Kilimanjaro, but a stunning peak in its own right with views of its famous neighbor.',
    firstAscent: '1904 - Fritz Jaeger',
    iconEmoji: '🌋',
  },
  {
    id: 'yanapaccha',
    name: 'Yanapaccha',
    elevation: 5460,
    elevationFt: 17913,
    latitude: -9.02639,
    longitude: -77.57694,
    country: 'Peru',
    range: 'Cordillera Blanca',
    category: 'andes',
    difficulty: 'Moderate-Difficult',
    description: 'A striking glaciated peak in the Cordillera Blanca near the scenic Llanganuco Valley. Less crowded than nearby Pisco, Yanapaccha offers moderately steep snow slopes with some crevasse negotiation — an ideal acclimatization climb for experienced mountaineers. The name means "black waterfall" in Quechua, though its west face gleams white with glacial ice.',
    firstAscent: '1954 - Ortenburger, Michael, Matthews, Irvin, Creswell & Ayres',
    iconEmoji: '🏔️',
  },
];
