/**
 * Mountain peak icons — bundled locally for instant load + offline support.
 * Each icon is a transparent PNG cutout stored in assets/images/peaks/.
 */

import type { ImageRequireSource } from 'react-native';

const MOUNTAIN_ICON_MAP: Record<string, ImageRequireSource> = {
  'everest': require('../assets/images/peaks/everest.png'),
  'aconcagua': require('../assets/images/peaks/aconcagua.png'),
  'denali': require('../assets/images/peaks/denali.png'),
  'kilimanjaro': require('../assets/images/peaks/kilimanjaro.png'),
  'elbrus': require('../assets/images/peaks/elbrus.png'),
  'vinson': require('../assets/images/peaks/vinson.png'),
  'carstensz': require('../assets/images/peaks/carstensz.png'),
  'k2': require('../assets/images/peaks/k2.png'),
  'kangchenjunga': require('../assets/images/peaks/kangchenjunga.png'),
  'lhotse': require('../assets/images/peaks/lhotse.png'),
  'makalu': require('../assets/images/peaks/makalu.png'),
  'cho-oyu': require('../assets/images/peaks/cho-oyu.png'),
  'dhaulagiri': require('../assets/images/peaks/dhaulagiri.png'),
  'manaslu': require('../assets/images/peaks/manaslu.png'),
  'nanga-parbat': require('../assets/images/peaks/nanga-parbat.png'),
  'annapurna': require('../assets/images/peaks/annapurna.png'),
  'gasherbrum1': require('../assets/images/peaks/gasherbrum1.png'),
  'broad-peak': require('../assets/images/peaks/broad-peak.png'),
  'gasherbrum2': require('../assets/images/peaks/gasherbrum2.png'),
  'shishapangma': require('../assets/images/peaks/shishapangma.png'),
  'mt-elbert': require('../assets/images/peaks/mt-elbert.png'),
  'mt-massive': require('../assets/images/peaks/mt-massive.png'),
  'mt-harvard': require('../assets/images/peaks/mt-harvard.png'),
  'blanca-peak': require('../assets/images/peaks/blanca-peak.png'),
  'la-plata': require('../assets/images/peaks/la-plata.png'),
  'uncompahgre': require('../assets/images/peaks/uncompahgre.png'),
  'crestone-peak': require('../assets/images/peaks/crestone-peak.png'),
  'mt-lincoln': require('../assets/images/peaks/mt-lincoln.png'),
  'grays-peak': require('../assets/images/peaks/grays-peak.png'),
  'torreys-peak': require('../assets/images/peaks/torreys-peak.png'),
  'quandary-peak': require('../assets/images/peaks/quandary-peak.png'),
  'longs-peak': require('../assets/images/peaks/longs-peak.png'),
  'pikes-peak': require('../assets/images/peaks/pikes-peak.png'),
  'capitol-peak': require('../assets/images/peaks/capitol-peak.png'),
  'maroon-peak': require('../assets/images/peaks/maroon-peak.png'),
  'mont-blanc': require('../assets/images/peaks/mont-blanc.png'),
  'matterhorn': require('../assets/images/peaks/matterhorn.png'),
  'eiger': require('../assets/images/peaks/eiger.png'),
  'jungfrau': require('../assets/images/peaks/jungfrau.png'),
  'gran-paradiso': require('../assets/images/peaks/gran-paradiso.png'),
  'monte-rosa': require('../assets/images/peaks/monte-rosa.png'),
  'weisshorn': require('../assets/images/peaks/weisshorn.png'),
  'dom': require('../assets/images/peaks/dom.png'),
  'grossglockner': require('../assets/images/peaks/grossglockner.png'),
  'zugspitze': require('../assets/images/peaks/zugspitze.png'),
  'dent-blanche': require('../assets/images/peaks/dent-blanche.png'),
  'aiguille-verte': require('../assets/images/peaks/aiguille-verte.png'),
  'grandes-jorasses': require('../assets/images/peaks/grandes-jorasses.png'),
  'triglav': require('../assets/images/peaks/triglav.png'),
  'ojos-del-salado': require('../assets/images/peaks/ojos-del-salado.png'),
  'huascaran': require('../assets/images/peaks/huascaran.png'),
  'chimborazo': require('../assets/images/peaks/chimborazo.png'),
  'cotopaxi': require('../assets/images/peaks/cotopaxi.png'),
  'illimani': require('../assets/images/peaks/illimani.png'),
  'huayna-potosi': require('../assets/images/peaks/huayna-potosi.png'),
  'alpamayo': require('../assets/images/peaks/alpamayo.png'),
  'fitz-roy': require('../assets/images/peaks/fitz-roy.png'),
  'cerro-torre': require('../assets/images/peaks/cerro-torre.png'),
  'sajama': require('../assets/images/peaks/sajama.png'),
  'volcan-lanin': require('../assets/images/peaks/volcan-lanin.png'),
  'mercedario': require('../assets/images/peaks/mercedario.png'),
  'ama-dablam': require('../assets/images/peaks/ama-dablam.png'),
  'island-peak': require('../assets/images/peaks/island-peak.png'),
  'mera-peak': require('../assets/images/peaks/mera-peak.png'),
  'pumori': require('../assets/images/peaks/pumori.png'),
  'baruntse': require('../assets/images/peaks/baruntse.png'),
  'lobuche-east': require('../assets/images/peaks/lobuche-east.png'),
  'annapurna-south': require('../assets/images/peaks/annapurna-south.png'),
  'machapuchare': require('../assets/images/peaks/machapuchare.png'),
  'tilicho-peak': require('../assets/images/peaks/tilicho-peak.png'),
  'mt-rainier': require('../assets/images/peaks/mt-rainier.png'),
  'mt-hood': require('../assets/images/peaks/mt-hood.png'),
  'mt-shasta': require('../assets/images/peaks/mt-shasta.png'),
  'mt-whitney': require('../assets/images/peaks/mt-whitney.png'),
  'mt-fuji': require('../assets/images/peaks/mt-fuji.png'),
  'aoraki': require('../assets/images/peaks/aoraki.png'),
  'mt-kenya': require('../assets/images/peaks/mt-kenya.png'),
  'mt-stanley': require('../assets/images/peaks/mt-stanley.png'),
  'toubkal': require('../assets/images/peaks/toubkal.png'),
  'mt-olympus': require('../assets/images/peaks/mt-olympus.png'),
  'ben-nevis': require('../assets/images/peaks/ben-nevis.png'),
  'mt-elbrus-west': require('../assets/images/peaks/mt-elbrus-west.png'),
  'mt-kinabalu': require('../assets/images/peaks/mt-kinabalu.png'),
  'orizaba': require('../assets/images/peaks/orizaba.png'),
  'iztaccihuatl': require('../assets/images/peaks/iztaccihuatl.png'),
  'mt-cook': require('../assets/images/peaks/mt-cook.png'),
  'mt-blanc-du-tacul': require('../assets/images/peaks/mt-blanc-du-tacul.png'),
  'lyskamm': require('../assets/images/peaks/lyskamm.png'),
  'mt-temple': require('../assets/images/peaks/mt-temple.png'),
  'mt-robson': require('../assets/images/peaks/mt-robson.png'),
  'mt-logan': require('../assets/images/peaks/mt-logan.png'),
  'mt-elbrus-traverse': require('../assets/images/peaks/mt-elbrus-traverse.png'),
  'musala': require('../assets/images/peaks/musala.png'),
  'gerlachovsky': require('../assets/images/peaks/gerlachovsky.png'),
  'mt-blanc-chamomix': require('../assets/images/peaks/mt-blanc-chamomix.png'),
  'mt-baker': require('../assets/images/peaks/mt-baker.png'),
  'volcano-teide': require('../assets/images/peaks/volcano-teide.png'),
  'cascade-14er-1': require('../assets/images/peaks/cascade-14er-1.png'),
  'mt-bierstadt': require('../assets/images/peaks/mt-bierstadt.png'),
  'mt-sneffels': require('../assets/images/peaks/mt-sneffels.png'),
  'iliniza-sur': require('../assets/images/peaks/iliniza-sur.png'),
  'iliniza-norte': require('../assets/images/peaks/iliniza-norte.png'),
  'cayambe': require('../assets/images/peaks/cayambe.png'),
  'lenin-peak': require('../assets/images/peaks/lenin-peak.png'),
  'meru-sharks-fin': require('../assets/images/peaks/meru-sharks-fin.png'),
  'shivling': require('../assets/images/peaks/shivling.png'),
  'aiguille-du-dru': require('../assets/images/peaks/aiguille-du-dru.png'),
  'piz-badile': require('../assets/images/peaks/piz-badile.png'),
  'mt-hunter': require('../assets/images/peaks/mt-hunter.png'),
  'mt-waddington': require('../assets/images/peaks/mt-waddington.png'),
  'torres-del-paine': require('../assets/images/peaks/torres-del-paine.png'),
  'paine-grande': require('../assets/images/peaks/paine-grande.png'),
  'grand-teton': require('../assets/images/peaks/grand-teton.png'),
  'nuptse': require('../assets/images/peaks/nuptse.png'),
  'rakaposhi': require('../assets/images/peaks/rakaposhi.png'),
  'khan-tengri': require('../assets/images/peaks/khan-tengri.png'),
  'pobeda-peak': require('../assets/images/peaks/pobeda-peak.png'),
  'popocatepetl': require('../assets/images/peaks/popocatepetl.png'),
  'mt-st-helens': require('../assets/images/peaks/mt-st-helens.png'),
  'tre-cime': require('../assets/images/peaks/tre-cime.png'),
  'mt-meru-tanzania': require('../assets/images/peaks/mt-meru-tanzania.png'),
  'yanapaccha': require('../assets/images/peaks/yanapaccha.png'),
  'monch': require('../assets/images/peaks/monch.png'),
  'kosciuszko': require('../assets/images/peaks/kosciuszko.png'),
  'half-dome': require('../assets/images/peaks/half-dome.png'),
  'table-mountain': require('../assets/images/peaks/table-mountain.png'),
  'shkhara': require('../assets/images/peaks/shkhara.png'),
  'mount-rinjani': require('../assets/images/peaks/mount-rinjani.png'),
  'mount-agung': require('../assets/images/peaks/mount-agung.png'),
  'mount-mayon': require('../assets/images/peaks/mount-mayon.png'),
  'mount-vesuvius': require('../assets/images/peaks/mount-vesuvius.png'),
  'villarrica': require('../assets/images/peaks/villarrica.png'),
  'mount-taranaki': require('../assets/images/peaks/mount-taranaki.png'),
  'mount-ngauruhoe': require('../assets/images/peaks/mount-ngauruhoe.png'),
  'mount-erebus': require('../assets/images/peaks/mount-erebus.png'),
  'sakurajima': require('../assets/images/peaks/sakurajima.png'),
  'mount-assiniboine': require('../assets/images/peaks/mount-assiniboine.png'),
  'el-capitan': require('../assets/images/peaks/el-capitan.png'),
  'marmolada': require('../assets/images/peaks/marmolada.png'),
  'piz-bernina': require('../assets/images/peaks/piz-bernina.png'),
  'antisana': require('../assets/images/peaks/antisana.png'),
  'el-altar': require('../assets/images/peaks/el-altar.png'),
  'artesonraju': require('../assets/images/peaks/artesonraju.png'),
  'snowdon': require('../assets/images/peaks/snowdon.png'),
  'scafell-pike': require('../assets/images/peaks/scafell-pike.png'),
  'mount-giluwe': require('../assets/images/peaks/mount-giluwe.png'),
  'mount-sidley': require('../assets/images/peaks/mount-sidley.png'),
  'carrauntoohil': require('../assets/images/peaks/carrauntoohil.png'),
  'galdhopiggen': require('../assets/images/peaks/galdhopiggen.png'),
  'mount-kailash': require('../assets/images/peaks/mount-kailash.png'),
  'mount-etna': require('../assets/images/peaks/mount-etna.png'),
  'mauna-kea': require('../assets/images/peaks/mauna-kea.png'),
};

const DEFAULT_ICON: ImageRequireSource = require('../assets/images/peaks/default.png');

/**
 * Returns the local bundled image source for a mountain peak icon.
 * Falls back to the default mountain icon for unknown/custom peaks.
 */
export function getMountainIconSource(mountainId: string): ImageRequireSource {
  return MOUNTAIN_ICON_MAP[mountainId] ?? DEFAULT_ICON;
}
